"""
Fixed-mBERT prompt tuning for multilingual fact prediction.


The prompt tokens are backed by mBERT's spare [unused1]..[unused99] vocab
ids, so no vocabulary resizing is needed -- their embeddings are simply
overwritten with a small trainable nn.Embedding before every forward pass.

Insertion positions (n = --num_prompt_tokens, [M] = the masked answer span):
    front:  [CLS] P_1..P_n  <query text>                [M]  [SEP]
    middle: [CLS] <query text before the answer> P_1..P_n [M]  <rest>  [SEP]
    back:   [CLS] <query text>                    [M]  P_1..P_n  [SEP]

Usage:
    # train directly from a language code (reuses load_lang_data.py's loader)
    python scripts/model.py --lang fr --num_prompt_tokens 10 --position front --epochs 10

    # or train from a CSV already generated by load_lang_data.py
    python scripts/model.py --csv data/query_fact/fr.csv --position middle --epochs 10
"""
import sys
import os
import csv
import random
import argparse
from os.path import dirname, abspath, join
from typing import Dict, List, Optional, Tuple

ROOT = dirname(dirname(abspath(__file__)))
sys.path.insert(0, join(ROOT, 'scripts'))

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModelForMaskedLM

from load_lang_data import load_language_data, DATASET

MASK_PLACEHOLDER = '[MASK]'
MAX_UNUSED = 99  # bert-base-multilingual-cased reserves [unused1]..[unused99]



def get_prompt_token_ids(tokenizer, n: int) -> List[int]:
    if n <= 0:
        raise ValueError('--num_prompt_tokens must be positive')
    if n > MAX_UNUSED:
        raise ValueError(f'--num_prompt_tokens={n} exceeds the {MAX_UNUSED} spare [unused] '
                          f'ids in this tokenizer\'s vocabulary')
    tokens = [f'[unused{i + 1}]' for i in range(n)]
    ids = tokenizer.convert_tokens_to_ids(tokens)
    if tokenizer.unk_token_id in ids:
        raise ValueError('this tokenizer has no [unusedN] reserved tokens; '
                          'pick a --model with spare vocab slots (e.g. bert-base-multilingual-cased)')
    return ids


class SoftPromptEncoder(nn.Module):

    def __init__(self, num_prompt_tokens: int, hidden_size: int):
        super().__init__()
        self.embedding = nn.Embedding(num_prompt_tokens, hidden_size)
        nn.init.normal_(self.embedding.weight, std=0.02)

    def forward(self, batch_size: int, device: torch.device) -> torch.Tensor:
        idx = torch.arange(self.embedding.num_embeddings, device=device)
        return self.embedding(idx).unsqueeze(0).expand(batch_size, -1, -1)  # (batch, n, hidden)


class PromptTunedMLM(nn.Module):


    def __init__(self, model_name: str, num_prompt_tokens: int):
        super().__init__()
        self.lm = AutoModelForMaskedLM.from_pretrained(model_name)
        for p in self.lm.parameters():
            p.requires_grad = False
        self.hidden_size = self.lm.config.hidden_size
        self.prompt_encoder = SoftPromptEncoder(num_prompt_tokens, self.hidden_size)

    def train(self, mode: bool = True):
        super().train(mode)
        self.lm.eval()  # keep the frozen backbone deterministic (dropout off) regardless
        return self

    def trainable_parameters(self):
        return self.prompt_encoder.parameters()

    def forward(self, input_ids, attention_mask, prompt_mask, labels=None):
        inputs_embeds = self.lm.get_input_embeddings()(input_ids).clone()
        batch_size = input_ids.size(0)
        prompt_embeds = self.prompt_encoder(batch_size, input_ids.device)  # (B, n, H)
        inputs_embeds[prompt_mask] = prompt_embeds.reshape(-1, self.hidden_size).to(inputs_embeds.dtype)
        return self.lm(inputs_embeds=inputs_embeds, attention_mask=attention_mask, labels=labels)


def load_examples(args) -> List[Dict]:
    if args.csv:
        with open(args.csv, encoding='utf-8') as fin:
            examples = list(csv.DictReader(fin))
        print(f'loaded {len(examples)} facts from {args.csv}', file=sys.stderr)
    else:
        examples, stats = load_language_data(
            lang=args.lang,
            probe=args.probe,
            portion=args.portion,
            pids=args.pids.split(',') if args.pids else None,
            num_mask=1,
            mask_token=MASK_PLACEHOLDER,
            use_inflection=not args.no_inflect,
            limit=args.limit,
        )
        print(f'loaded {len(examples)} facts for lang={args.lang} '
              f'(#relations {stats["num_relations"]}, #errors {stats["num_errors"]})', file=sys.stderr)
    return examples


def build_features(examples: List[Dict], tokenizer, prompt_ids: List[int],
                    position: str, max_length: int) -> Tuple[List[Dict], int]:
    """Turn raw {query, answer, ...} facts into fixed input_ids/prompt_mask/labels,
    with `prompt_ids` spliced in at `position` relative to the masked answer span."""
    cls_id, sep_id = tokenizer.cls_token_id, tokenizer.sep_token_id
    n = len(prompt_ids)
    features, n_skipped = [], 0

    for ex in examples:
        query, answer = ex['query'], ex['answer']
        if MASK_PLACEHOLDER not in query:
            n_skipped += 1
            continue
        pre_text, post_text = query.split(MASK_PLACEHOLDER, 1)
        answer_ids = tokenizer.encode(answer, add_special_tokens=False)
        if not answer_ids:
            n_skipped += 1
            continue
        pre_ids = tokenizer.encode(pre_text, add_special_tokens=False)
        post_ids = tokenizer.encode(post_text, add_special_tokens=False)
        mask_ids = [tokenizer.mask_token_id] * len(answer_ids)

        if position == 'front':
            body = prompt_ids + pre_ids + mask_ids + post_ids
            prompt_start = 1
            mask_start = 1 + n + len(pre_ids)
        elif position == 'back':
            body = pre_ids + mask_ids + post_ids + prompt_ids
            mask_start = 1 + len(pre_ids)
            prompt_start = 1 + len(pre_ids) + len(mask_ids) + len(post_ids)
        elif position == 'middle':
            body = pre_ids + prompt_ids + mask_ids + post_ids
            prompt_start = 1 + len(pre_ids)
            mask_start = 1 + len(pre_ids) + n
        else:
            raise ValueError(f'unknown --position {position}')

        input_ids = [cls_id] + body + [sep_id]
        if len(input_ids) > max_length:
            n_skipped += 1
            continue

        prompt_mask = [False] * len(input_ids)
        for i in range(prompt_start, prompt_start + n):
            prompt_mask[i] = True

        labels = [-100] * len(input_ids)
        for i, tok_id in enumerate(answer_ids):
            labels[mask_start + i] = tok_id

        features.append({
            'input_ids': input_ids,
            'prompt_mask': prompt_mask,
            'labels': labels,
            'relation': ex.get('relation'),
            'sub_label': ex.get('sub_label'),
            'obj_label': ex.get('obj_label'),
        })

    return features, n_skipped


class FeatureDataset(Dataset):
    def __init__(self, features: List[Dict]):
        self.features = features

    def __len__(self):
        return len(self.features)

    def __getitem__(self, idx):
        return self.features[idx]


def make_collate_fn(pad_id: int):
    def collate_fn(batch: List[Dict]) -> Dict[str, torch.Tensor]:
        max_len = max(len(b['input_ids']) for b in batch)
        input_ids, attention_mask, prompt_mask, labels = [], [], [], []
        for b in batch:
            pad_n = max_len - len(b['input_ids'])
            input_ids.append(b['input_ids'] + [pad_id] * pad_n)
            attention_mask.append([1] * len(b['input_ids']) + [0] * pad_n)
            prompt_mask.append(b['prompt_mask'] + [False] * pad_n)
            labels.append(b['labels'] + [-100] * pad_n)
        return {
            'input_ids': torch.tensor(input_ids, dtype=torch.long),
            'attention_mask': torch.tensor(attention_mask, dtype=torch.long),
            'prompt_mask': torch.tensor(prompt_mask, dtype=torch.bool),
            'labels': torch.tensor(labels, dtype=torch.long),
        }
    return collate_fn



def set_seed(seed: int):
    random.seed(seed)
    torch.manual_seed(seed)


@torch.no_grad()
def evaluate(model: PromptTunedMLM, loader: DataLoader, device: torch.device) -> Tuple[float, float]:
    model.eval()
    total, correct, loss_sum, n_batches = 0, 0, 0.0, 0
    for batch in loader:
        batch = {k: v.to(device) for k, v in batch.items()}
        out = model(**batch)
        loss_sum += out.loss.item()
        n_batches += 1
        preds = out.logits.argmax(-1)
        labels = batch['labels']
        mask_positions = labels != -100
        for i in range(labels.size(0)):
            pos = mask_positions[i]
            if pos.sum() == 0:
                continue
            total += 1
            correct += int(torch.equal(preds[i][pos], labels[i][pos]))
    model.train()
    return loss_sum / max(1, n_batches), correct / max(1, total)


def main():
    parser = argparse.ArgumentParser(description='fixed-mBERT prompt tuning for fact prediction')
    # data
    parser.add_argument('--lang', type=str, default=None, help='language code (loads via load_lang_data.py)')
    parser.add_argument('--csv', type=str, default=None,
                         help='pre-generated CSV from load_lang_data.py; if given, overrides --lang')
    parser.add_argument('--probe', type=str, choices=list(DATASET.keys()), default='mlama')
    parser.add_argument('--portion', type=str, choices=['all', 'trans', 'non'], default='trans')
    parser.add_argument('--pids', type=str, default=None, help='comma-separated relation ids to include')
    parser.add_argument('--limit', type=int, default=None, help='cap the number of facts loaded')
    parser.add_argument('--no_inflect', action='store_true')
    # prompt / model
    parser.add_argument('--model', type=str, default='bert-base-multilingual-cased')
    parser.add_argument('--num_prompt_tokens', type=int, default=10)
    parser.add_argument('--position', type=str, choices=['front', 'middle', 'back'], default='front')
    parser.add_argument('--max_length', type=int, default=128)
    # training
    parser.add_argument('--epochs', type=int, default=10)
    parser.add_argument('--batch_size', type=int, default=32)
    parser.add_argument('--lr', type=float, default=1e-2,
                         help='prompt tuning trains a tiny embedding table, so this is usually '
                              'much higher than a full-finetuning learning rate')
    parser.add_argument('--val_frac', type=float, default=0.1)
    parser.add_argument('--seed', type=int, default=42)
    parser.add_argument('--save_path', type=str, default=None,
                         help='where to save the trained prompt embeddings (default: runs/<tag>_<position>_<n>.pt)')
    parser.add_argument('--no_cuda', action='store_true')
    args = parser.parse_args()

    if not args.csv and not args.lang:
        parser.error('provide --lang or --csv')

    set_seed(args.seed)
    device = torch.device('cuda' if torch.cuda.is_available() and not args.no_cuda else 'cpu')

    print(f'loading tokenizer {args.model} ...', file=sys.stderr)
    tokenizer = AutoTokenizer.from_pretrained(args.model)
    prompt_ids = get_prompt_token_ids(tokenizer, args.num_prompt_tokens)

    raw_examples = load_examples(args)
    features, n_skipped = build_features(raw_examples, tokenizer, prompt_ids, args.position, args.max_length)
    print(f'built {len(features)} training examples ({n_skipped} skipped: no mask placeholder, '
          f'empty answer, or too long)', file=sys.stderr)
    if len(features) < 2:
        raise SystemExit('not enough examples to train on')

    random.shuffle(features)
    n_val = max(1, int(len(features) * args.val_frac))
    val_features, train_features = features[:n_val], features[n_val:]

    collate_fn = make_collate_fn(tokenizer.pad_token_id)
    train_loader = DataLoader(FeatureDataset(train_features), batch_size=args.batch_size,
                               shuffle=True, collate_fn=collate_fn)
    val_loader = DataLoader(FeatureDataset(val_features), batch_size=args.batch_size,
                             shuffle=False, collate_fn=collate_fn)

    print(f'loading frozen {args.model} ...', file=sys.stderr)
    model = PromptTunedMLM(args.model, args.num_prompt_tokens).to(device)
    model.train()
    n_trainable = sum(p.numel() for p in model.trainable_parameters())
    n_frozen = sum(p.numel() for p in model.lm.parameters())
    print(f'trainable (prompt) params: {n_trainable:,}  |  frozen {args.model} params: {n_frozen:,}',
          file=sys.stderr)

    optimizer = torch.optim.AdamW(model.trainable_parameters(), lr=args.lr)

    for epoch in range(1, args.epochs + 1):
        model.train()
        total_loss = 0.0
        for batch in train_loader:
            batch = {k: v.to(device) for k, v in batch.items()}
            optimizer.zero_grad()
            out = model(**batch)
            out.loss.backward()
            optimizer.step()
            total_loss += out.loss.item()
        val_loss, val_acc = evaluate(model, val_loader, device)
        print(f'epoch {epoch}/{args.epochs}  train_loss {total_loss / len(train_loader):.4f}  '
              f'val_loss {val_loss:.4f}  val_exact_match {val_acc:.4f}')

    save_path = args.save_path
    if save_path is None:
        os.makedirs(join(ROOT, 'runs'), exist_ok=True)
        tag = args.lang or os.path.splitext(os.path.basename(args.csv))[0]
        save_path = join(ROOT, 'runs', f'{tag}_{args.position}_{args.num_prompt_tokens}.pt')
    else:
        out_dir = dirname(abspath(save_path))
        if out_dir:
            os.makedirs(out_dir, exist_ok=True)

    torch.save({
        'prompt_encoder_state_dict': model.prompt_encoder.state_dict(),
        'model_name': args.model,
        'num_prompt_tokens': args.num_prompt_tokens,
        'position': args.position,
        'prompt_token_ids': prompt_ids,
    }, save_path)
    print(f'saved trained prompt embeddings to {save_path}')


if __name__ == '__main__':
    main()
